import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Navbar from "./components/Navbar";
import { createSupabaseServerClient } from "@/app/lib/supabase/server";
import { getUserData } from "@/app/lib/user";
import { ThemeProvider } from "./components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import UrlToastHandler from "@/app/components/UrlToastHandler";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "BFriends",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/bfriends-full.svg", type: "image/svg+xml" },
      { url: "/favicon.ico", type: "image/x-icon", sizes: "any" },
      { url: "/favicon-16x16.png", type: "image/png", sizes: "16x16" },
      { url: "/favicon-32x32.png", type: "image/png", sizes: "32x32" },
    ],
    apple: [{ url: "/apple-touch-icon.png", type: "image/png" }],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  const userData = user ? await getUserData(user.id) : null;

  return (
    <html lang="en" className={GeistSans.className} suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader
            height={5}
            speed={800}
            color="hsl(221.2 83.2% 53.3%)"
          />
          <Navbar user={user} userData={userData} />
          <main>{children}</main>
          <UrlToastHandler />
          <Toaster position="bottom-right" richColors closeButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
